# Generated by Django 2.0.5 on 2018-05-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20180503_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(default=True, max_length=32),
        ),
    ]
